name: Sync Upstream to Sync Branch

on:
  schedule:
    - cron: '15 2 * * *'   # 10:15
    - cron: '30 2 * * *'   # 10:30
    - cron: '0 3 * * *'    # 11:00
    - cron: '15 8 * * *'   # 16:15
    - cron: '30 8 * * *'   # 16:30
    - cron: '0 9 * * *'    # 17:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: sync            
          persist-credentials: true

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/Kengxxiao/ArknightsGameData.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Reset sync branch to upstream/master
        run: |
          git reset --hard upstream/master
          git push origin sync --force
