name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the forked repo
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Foehn-Shit"  # 替换为你的 GitHub 用户名
          git config --global user.email "mzt1214164232@gmail.com"  # 替换为你的电子邮件

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/Kengxxiao/ArknightsGameData.git
          git fetch upstream
          git checkout master  # 或者你使用的主要分支
          git merge upstream/master
          git push origin master  # 将更改推送到你的 fork
