name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the forked repo
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Foehn-Shit"  # 替换为你的 GitHub 用户名
          git config --global user.email "mzt1214164232@gmail.com"  # 替换为你的电子邮件

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/Kengxxiao/ArknightsGameData.git  # 添加目标仓库
          git fetch upstream  # 获取上游更新
          git checkout master  # 切换到你的主分支
          git merge upstream/master  # 合并目标仓库的主分支到你的主分支

      - name: Push changes
        run: git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Foehn-Shit/ArknightsGameData.git master  # 将更改推送到你的仓库

