name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周同步一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repository (fork)
      - name: Checkout Fork Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: master  # 使用 master 分支

      # Set GitHub user info for commit
      - name: Set GitHub User
        run: |
          git config --global user.email "mzt1214164232@gmail.com"
          git config --global user.name "Foehn-Shit"  # 将YourGitHubUsername替换为你的GitHub用户名

      # Add upstream repository
      - name: Add Upstream Repository
        run: git remote add upstream https://github.com/Kengxxiao/ArknightsGameData.git

      # Fetch upstream changes
      - name: Fetch Upstream Changes
        run: git fetch upstream

      # Merge upstream changes into fork's master branch
      - name: Merge Upstream Changes
        run: git merge upstream/master --allow-unrelated-histories

      # Push changes to the forked repository
      - name: Push Changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master
